# ---------- Use Testnet for "development" so npm run dev binds to testnet ----------

[development]
accounts = ["default"]

[development.network]
rpc-url = "https://soroban-testnet.stellar.org"
network-passphrase = "Test SDF Network ; September 2015"
run-locally = false

[development.contracts]

[development.contracts.non_fungible_contract]
# Your deployed testnet contract ID:
id = "CBIPHUNJIHE3HTLE2BCCEKVON5PYC7LPT6HLX46SYME4VYBENTOS5PVU"
# IMPORTANT: do NOT put constructor_args here (we're not instantiating locally)
# wasm_hash is optional; client binding only needs the id
