[development]
accounts = ["default"]

[development.network]
rpc-url = "http://localhost:8000/rpc"
network-passphrase = "Standalone Network ; February 2017"
run-locally = true

[development.contracts]

[development.contracts.non_fungible_contract]
constructor_args = "--admin andlopvic --upgrader andlopvic --pauser andlopvic --minter andlopvic"
